### ISSUE TITLE
how to reduce spacing between two commands

### ISSUE THREAD

**Issue by ghost** [cmilr/Git-Beautify-For-MacOS-Terminal#2]
I love your Terminal Beautify solution, my only issue is the spacing between 2 commands/prompts in the terminal. 
So, I would like to reduce this spacing, how can I accomplish that? see for example the space between two commands/prompts in the screenshot below.
![image](https://user-images.githubusercontent.com/6693969/32854959-28058806-c9f5-11e7-9416-89f0357fab48.png)

**Comment by cmilr** [comment]
_I'm glad you enjoy it_—I think the easiest way to shrink that space up would be to edit line 108, removing the first new line character at the beginning of the string, so that it looks like this:

`printf "$txtblu%s @ $txtblu%s $txtpur%s\n$txtrst" "$USER" "$PWD"`

That should move your prompt up by one line. You'll need to restart your terminal after making these changes.

There may be other new lines you could remove, but I'm buried in work at the moment, so I don't have time to check. Hope this helps!

**Comment by ghost** [comment]
thanks a lot @cmilr
